name: Npm start

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd ./all_in-docker/server
          npm install

      - name: Build
        run: 
          cd ./all_in-docker/server
          node index.js